services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    environment:
      pythonVersion: 3.10
    autoDeploy: true
